### ISSUE TITLE
add credits in group model and consume from there

### ISSUE THREAD

**Issue by vinibgoulart** [vinibgoulart/wpp-playground#11]
- [ ] add field `credits`
- [ ] consume credits when receive some message
- [ ] min: 5 points (all messages)
- [ ] gpt - 8 points
- [ ] resume - 10 points
- [ ] middleware with validation
- [ ] ignore `defaultMessage`, `!init`, `!resume-start` and `!resume-stop`

**Comment by samueldurantes** [comment]
I can grab this one, what is the points default that a group starts?

**Comment by vinibgoulart** [comment]
start with 200 credits
