### ISSUE TITLE
!commands command

### ISSUE THREAD

**Issue by vinibgoulart** [vinibgoulart/wpp-playground#15]
- [ ] add command `!commands`
- [ ] list all commands
- [ ] explain each command

**Comment by akinncar** [comment]
I can grab this one, I suggest `!help` instead of `!commands`

**Comment by samueldurantes** [comment]
> I can grab this one, I suggest `!help` instead of `!commands`

How do you think about consuming the descriptions of each command?

I think that each command should be an object, where you pass name, description, and action, like this:

```ts
export default {
  name: 'help',
  description: 'List all commands',
  action: async () => {},
}
```
