### ISSUE TITLE
add command to resume last x messages

### ISSUE THREAD

**Issue by vinibgoulart** [vinibgoulart/wpp-playground#20]
- [ ] use `fetchMessages`
- [ ] https://docs.wwebjs.dev/Chat.html#fetchMessages
- [ ] new command `!resume-qty <x>`
- [ ] get the last `<x>` messages and make a prompt for gpt api

**Comment by fiamon** [comment]
is there a deadline? i can do this

**Comment by 2yuri** [comment]
@vinibgoulart I can do that! can you assign it to me?
